title: DiscordRDA
description: Modern Ruby library for Discord bot development
baseurl: "/discordRDA"
url: "https://kleeedolinux.github.io"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  docs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md
  - package.json
  - pnpm-lock.yaml
  - .gitignore
  - public/.nojekyll

sass:
  sass_dir: _sass
  style: compressed
